#!/usr/bin/expect -f
set timeout -1
spawn ./passbox new
match_max 100000
expect -exact "break\r
Name: "
send -- "Test\r"
expect -exact "Test\r
Username: "
send -- "Test\r"
expect -exact "Test\r
Generate password? (y/n, default: y) "
send -- "n\r"
expect -exact "n\r
Enter password for \"Test\": "
send -- "T"
expect -exact "*"
send -- "e"
expect -exact "*"
send -- "s"
expect -exact "*"
send -- "t"
expect -exact "*"
send -- "\r"
expect eof
